stages:
  - pre
  - build
  - release
  - deploy

sonarqube-check:
  stage: pre
  image:
    name: sonarsource/sonar-scanner-cli:latest
    pull_policy: if-not-present
    entrypoint: [ "" ]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  # 缓存SonarQube插件
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.projectKey=TISIHSCP-PAD
      -Dsonar.sources=.
      -Dsonar.host.url=http://172.16.175.14:9000
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.scanner.timeoutSeconds=300
  allow_failure: true
  only:
    # 合并请求和特定分支
    - HCSP-FRONTEND-VUE-DEV
    - tisi_cicd

cache:
  key:
    files:
      - hcsp-frontend/package.json
      - hcsp-frontend/package-lock.json
  paths:
    - hcsp-frontend/node_modules/


build:
  stage: build
  image: node:16.19.1  # 使用适合您项目的 Node.js 版本
  script:
    - pwd
    - ls -la
    # 或者 yarn install，取决于使用的包管理器
    - npm install
    # 构建
    - npm run build
    - mkdir -p $CI_PROJECT_DIR/dist
    - rm -rf $CI_PROJECT_DIR/dist/*
    # 将 dist 目录复制到 artifacts 目录下
    - cp -r dist/* $CI_PROJECT_DIR/dist/
  artifacts:
    name: "dist-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
    expire_in: 1 hour
  only:
    # 合并请求和特定分支
    - HCSP-FRONTEND-VUE-SIT
    - tisi_cicd


sentry_release:
  stage: release
  image:
    name: getsentry/sentry-cli:latest
  script:
    - pwd
    - ls -la
    - export SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN"
    - export SENTRY_ORG="$SENTRY_ORG"
    - export SENTRY_PROJECT="$SENTRY_PROJECT"
    # 如果使用的是自托管的Sentry，请取消下面这行的注释并设置正确的URL
    - export SENTRY_URL="https://tisi.sentry.io/"

    # 创建新的Sentry版本
    - sentry-cli releases new -p $SENTRY_PROJECT $CI_COMMIT_SHA

    # 设置提交数据
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHA


    # 上传 /dist/ 目录下的文件
    - sentry-cli releases files $CI_COMMIT_SHA upload-sourcemaps dist/js --url-prefix ~/js/

    # 完成发布
    - sentry-cli releases finalize $CI_COMMIT_SHA


    # 部署到生产环境（如果适用）
    - sentry-cli releases deploys $CI_COMMIT_SHA new -e production

    - pwd
    - ls -la
  only:
    # 合并请求和特定分支
    - HCSP-FRONTEND-VUE-SIT
    - tisi_cicd


variables:
  SENTRY_AUTH_TOKEN: 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
  SENTRY_ORG: tisi
  SENTRY_PROJECT: TISIHSCP-PAD
#
#deploy:
#  stage: deploy
#  script:
#    - rm -rf dist/js/*.map
#    - mkdir -p /cache/hcsp-frontend
#    - ls -al
#    - cp -r dist/* /cache/hcsp-frontend
#  # 只在特定分支上运行
#  only:
#    # 合并请求和特定分支
#    - HCSP-FRONTEND-VUE-SIT
#    - sunshu_cicd_build
#
#
#notify_feishu:
#  stage: deploy
#  image:
#    name: curlimages/curl:latest
#    pull_policy: if-not-present
#  script:
#    - |
#      curl -k -X POST -H "Content-Type:application/json" \
#      -d '{
#        "msg_type": "post",
#        "content": {
#          "post": {
#            "zh_cn": {
#              "title": "PROD01-TISIHCSP-ADMIN-VUE项目/分支：'"${CI_COMMIT_BRANCH/tool/}"'已发布",
#              "content": [
#                [
#                {
#                    "tag": "text",
#                    "text": "提交人: '"${CI_COMMIT_AUTHOR}"'\n"
#                  },
#                  {
#                    "tag": "text",
#                    "text": "本次更新内容：'"${CI_COMMIT_MESSAGE}"'\n"
#                  },
#
#                  {
#                    "tag": "a",
#                    "text": "查看流水线",
#                    "href": "'"${CI_PROJECT_URL}/-/pipelines/${CI_PIPELINE_ID}"'"
#                  }
#                ]
#              ]
#            }
#          }
#        }
#      }' \
#      https://open.feishu.cn/open-apis/bot/v2/hook/5c380c6b-e97b-4bad-987b-3d5d6117320c
#  only:
#    # 合并请求和特定分支
#    - HCSP-FRONTEND-VUE-SIT
#    - sunshu_cicd_build
#  when: on_success









